### PR TITLE
Portuguese support.

### PR DESCRIPTION
**Pull request by lazynessmind**
Added portugal and brasil portuguese translations.

### CODE REVIEW

**Comment by IntegratedQuantum** [comment]
Thank you!

Is there a particular reason why you only translated the menu texts?

**Comment by lazynessmind** [comment]
> Thank you!
> 
> Is there a particular reason why you only translated the menu texts?

I copied the the en_us.lang file and translated the existing ones

**Comment by IntegratedQuantum** [comment]
But the blocks and items still have their english names.

**Comment by lazynessmind** [comment]
For some reason mine didn't have the block keys.
I will fix it later.

**Pull request merged**
