### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by archbirdplus**
- [x] Fetch target-specific cubyz_deps.
- [x] Add option to build from local cubyz_deps.
- [x] Fetch headers separately from the binaries.
- [x] Link to official releases of the cubyz_deps.

Tangentially related to [this PR](https://github.com/PixelGuys/Cubyz-libs/pull/2).

### CODE REVIEW

**Comment by IntegratedQuantum** [comment]
I linked the release and made it work on my gnu linux.

It would be great if you could test if the linked macos libraries work on your machine.

**Comment by archbirdplus** [comment]
Looks like you didn't use my fork of GLFW. GLFW fails with `X11: Failed to load Xlib` because it doesn't attempt to dlopen the appropriate file.
But how did you cross-compile to MacOS? Did you use the MacOSX SDK headers repo?

**Comment by IntegratedQuantum** [comment]
No, I used the master branch, which has your PR merged.

For cross compilation I manually fetched all the necessary headers from the SDK headers repo.

**Comment by archbirdplus** [comment]
[Master branch](https://github.com/glfw/glfw/commits) does not have my PR merged. In the meantime, use mine: https://github.com/archbirdplus/glfw/releases/tag/Mac-x11

**Comment by IntegratedQuantum** [comment]
Oh, i didn't notice you made a PR in the glfw repo, I thought you meant the PR you made to Cubyz-libs.

I'll try building with you glfw version then.

**Comment by archbirdplus** [comment]
Compiles and runs. Will work out the bugs later

**Pull request merged**
