### PR TITLE
UI Texture Update

### LINKED ISSUE #361: Heart icon violates texture rules (132 excess colors in palette)
> If any of the following points are ignored, your texture will be rejected:
> ...
> 2. There must be at most 16 different colors in the entire texture.

### LINKED ISSUE #373: UI using block textures is too noisy
Here's the creative menu as it is now:
image
It's a menu very dense with information, filled with different colours, materials, patterns, shapes, etc... The textured UI, being just as detailed as the items inside of it, is distracting from the actual important information.

Here's the creative menu with flat colours (not representative of any kind of final product):
image
You can see how much more the items "pop" out of the menu, and generally, it's much cleaner

Things to note:
No, adding the updated textures to the UI will not fix this. 

Of course, doing this removes a lot of character from the UI. I think the idea of the UI being made of real materials is a good one, just not this execution.

### PR DESCRIPTION
**Pull request by careeoki**
Updates UI textures to match the newest block textures. Also improves the legibility of icons.
Fixes #373 and fixes #361 
image
image
Note that the hotbar is now opaque. I think it being translucent was nice, but to do that we need another texture/some code

### CODE REVIEW

**Comment by archbirdplus** [comment]
My thoughts
* looks a little too cartoonish for my taste
* scroll bar is really thin
* the checkboxes are amazing!
* +/- zoom icon is more intuitive
* red cross icon looks out of place in thickness and it's also somewhat out of bounds
Screenshot 2024-05-26 at 10 44 23

**Comment by careeoki** [comment]
I can't change the scrollbar because it is made in code, which is not my department. Same with the icon spacing/window title height.
Here's a different X:
image

**Comment by archbirdplus** [comment]
This X looks a little more natural. 
The inventory slider width is defined here if you want to try: https://github.com/PixelGuys/Cubyz/blob/master/src/gui/components/VerticalList.zig#L16C24-L16C25

**Comment by careeoki** [comment]
image

**Comment by archbirdplus** [comment]
Lol, you replaced all the tabs with spaces trying to edit that one line.

**Comment by careeoki** [comment]
I warned you!
The value 10 looked good. Someone else can do it for me in 30 seconds.

**Comment by tillpp** [comment]
Personally, i would say, the bigger red cross, looked better, but anyway:

could you make the inside of the red cross, a bit brighter for more contrast?
Compared to the zoom buttons,the cross doesn't seem to have that much contrast.
or maybe it is just me?

**Comment by archbirdplus** [comment]
See my PR on your PR. (?)

**Comment by IntegratedQuantum** [comment]
I prefer the thin red cross.

**Comment by careeoki** [comment]
I'm ready for this to be merged.
image

**Pull request merged**
