### PR TITLE
Add Italian translation.

### PR DESCRIPTION
**Pull request by MrLucio**

### CODE REVIEW

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]
You are missing a few language keys.
(Some of which are also not in the english translation yet)

```
block.cubyz.glow_crystal/red.name
block.cubyz.glow_crystal/dark_green.name
block.cubyz.glow_crystal/dark_gray.name
block.cubyz.glow_crystal/blue.name
block.cubyz.glow_crystal/light_blue.name
block.cubyz.glow_crystal/gray.name
block.cubyz.glow_crystal/yellow.name
block.cubyz.glow_crystal/cyan.name
block.cubyz.glow_crystal/brown.name
block.cubyz.glow_crystal/dark_red.name
block.cubyz.glow_crystal/purple.name
block.cubyz.glow_crystal/black.name
block.cubyz.glow_crystal/white.name
block.cubyz.glow_crystal/green.name
block.cubyz.glow_crystal/violet.name
block.cubyz.glow_crystal/orange.name
gui.cubyz.settings.discord
gui.cubyz.settings.language
gui.cubyz.settings.graphics
gui.cubyz.settings.keybindings
gui.cubyz.settings.done
gui.cubyz.general.off
gui.cubyz.general.on
gui.cubyz.mainmenu.settings
gui.cubyz.mainmenu.exit
gui.cubyz.mainmenu.singleplayer
gui.cubyz.mainmenu.multiplayer
```

**Comment by MrLucio** [comment]
I'm confused about the slash char inside the keys name since no other keys have it.

**Comment by IntegratedQuantum** [comment]
The slash is just like any other character. It can be used in the same way as underscore.
Wait let me update the english version, so you can see how to use it: c7f93ee

**Review by IntegratedQuantum — APPROVED** [review]
It's complete now. Thanks!

**Pull request merged**
