### PR TITLE
Basalt blocks & Lamp

### PR DESCRIPTION
**Pull request by careeoki**
Basalt is a new dark stone set. It could be found at volcanoes, at basalt column beaches, or underground in a cave biome, above lava caves.
image
I tried to make a volcano biome but all my results were too jank. You can imagine it with this tiny baby volcano.
image
The lamp is a new man-made light block.
image
image
I made the light from torches warmer, to have it look more like a hot flame. You can use the new lamp for a light closer to the old torch.
image
image
The light from uranium glass is much darker, to better resemble the glow it emits under UV light in real life. You can use green glowcrystal for a bright green light.
image

### CODE REVIEW

**Comment by IntegratedQuantum** [comment]
Nice, finally a dark gray stone type!

Having basalt bricks vertical seems like an odd thing to do, did you check how they look in a building?
Also have you thought about using this in the lava caves as well, maybe add some basalt stripes or something?

About the volcano, I'll take care of that after the PR has been merged.

**Comment by careeoki** [comment]
They look fine in builds, it's meant to resemble basalt columns, but if we would prefer it horizontal I can just rotate the texture. I have no preference.

**Comment by IntegratedQuantum** [comment]
Alright, I guess we can just go with it for now and rotate it later if other people have problems with it.

**Comment by pd76** [comment]
I think the basalt would look better rotated, since it matches how normal bricks are made
never seen anyone do bricks vertically before

**Pull request merged**
