### PR TITLE
Fix #676 Player keeps forwards momentum when sliding against block

### LINKED ISSUE #676: Player keeps forwards momentum when sliding against block
Not sure if intended. Here is a comparison between an old and new version.

https://github.com/user-attachments/assets/61308997-7641-4015-acc1-a1e14bad1b8b

### PR DESCRIPTION
**Pull request by ITR13**

### CODE REVIEW

**Comment by ITR13** [comment]
Fixes #676

**Comment by IntegratedQuantum** [comment]
I don't think this is the right fix. With your fix the velocity is set to zero one frame after the actual collision happened. This can have unintended side effects (e.g. it could make client side entity interpolations look wrong when a player walks into a wall).

**Comment by ITR13** [comment]
Changed it to check if it's the same as "move" instead. Since the return value is assigned directly with move if no collision happens we don't have to worry about floating point imprecision unless the player collides with a block and somehow moves the exact same distance as they should have.

**Comment by IntegratedQuantum** [comment]
Also please put the "fixes ..." in the main post in the future, otherwise github won't detect it and I need to manually close the issue.

**Comment by IntegratedQuantum** [comment]
Oh wait never mind, you put it in the issue as well, that also works.

**Comment by ITR13** [comment]
> Oh wait never mind, you put it in the commit as well, that also works.
Yeah, but it only showed the commit in the original Issue, not the PR, so I'll have to make sure to include it in the description of the main post too. I guess having it in the title wasn't enough.

**Pull request merged**
