### PR TITLE
Mahogany trees, updated jungle (somewhat)

### PR DESCRIPTION
**Pull request by careeoki**
Adds mahogany trees, for the jungle!
The jungle is still "(TODO)" since there's only so much I can do with the current biome parameters (specifically it needs #279, #519, and its own grass colour, which we haven't decided how to go about doing yet)
image
image
image

### CODE REVIEW

**Comment by IntegratedQuantum** [comment]
To be honest the jungle looks pretty similar to the regular forest, due to using similar colors for the log and the leaves.
Could you maybe make the leaves more saturated and give the stem a mossy/overgrown look?

**Comment by careeoki** [comment]
> To be honest the jungle looks pretty similar to the regular forest, due to using similar colors for the log and the leaves. Could you maybe make the leaves more saturated and give the stem a mossy/overgrown look?

I can try that.

**Comment by careeoki** [comment]
> I personally think the trees should be taller, but there is no way to do that without also making giant leaf orbs that lag heavily.

Yes, they absolutely should be, but it's not possible at the moment.

**Comment by careeoki** [comment]
New colours:
image
The log has small amounts of green in it. I found that adding more obvious moss makes it tile poorly and generally look ugly.
image
image

**Pull request merged**
